CREATE TABLE job_applications (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NULL,
    position VARCHAR(150) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'APPLIED',
    cover_letter TEXT NULL,
    years_experience INT NOT NULL DEFAULT 0,
    available_from DATE NULL,
    applied_date DATE NULL,
    work_type VARCHAR(50) NULL,
    salary_expectation INT NULL,
    notes TEXT NULL,
    portfolio_url VARCHAR(255) NULL,
    linkedin_url VARCHAR(255) NULL,
    remote_ok BOOLEAN NOT NULL DEFAULT FALSE,
    resume_file_name VARCHAR(255) NULL,
    resume_storage_name VARCHAR(255) NULL,
    resume_path VARCHAR(500) NULL,
    resume_content_type VARCHAR(150) NULL,
    resume_size BIGINT NULL,
    resume_category VARCHAR(100) NULL,
    resume_subcategory VARCHAR(100) NULL,
    resume_uploaded_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_job_applications_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
