spring.datasource.url=jdbc:mysql://localhost:3306/application_tracker
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.cors.allowed-origins=http://localhost:5173
app.jwt.secret=change-me-to-a-long-dev-secret-key-for-application-tracker-2026
app.jwt.expiration-ms=86400000
app.usajobs.user-agent=khemneupane84@gmail.com
app.usajobs.api-key=SIlonuPERFVHsmFrLuB9W2oEiwrhgx7LsB2HxZMBwGY=
app.bls.registration-key=b900776d590247b6b71a15e916fa2e97
