spring.application.name=application-tracker

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

app.cors.allowed-origins=
app.jwt.secret=change-me-to-a-long-dev-secret-key-for-application-tracker-2026
app.jwt.expiration-ms=86400000
app.usajobs.user-agent=khemneupane84@gmail.com
app.usajobs.api-key=SIlonuPERFVHsmFrLuB9W2oEiwrhgx7LsB2HxZMBwGY=
app.bls.registration-key=b900776d590247b6b71a15e916fa2e97
